version: '3'

services:
  proxy:
    container_name: proxy
    image: nginx:1.19
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./auth/htpasswd:/etc/nginx/htpasswd
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
      - dashboard-frontend:dashboard-frontend
      - dashboard-backend:dashboard-backend

  mongodb:
    image: mongo:4
    restart: always
    volumes:
      - ./data/db/:/data/db/
      - ./data/dump/:/dump/

  dashboard-backend:
    image: hilster/dashboard:latest
    restart: always
    environment:
      - ACTIVATION_KEY=AAAA-BBBB-CCCC-DDDD  # Change this activation key!
    volumes:
      - ./licenses/:/licenses/
      - ./dashboard/:/configuration/
      - ./logs/:/var/log/
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    command: dashboard-backend /configuration/dashboard.yml

  dashboard-frontend:
    image: hilster/dashboard:latest
    restart: always
    volumes:
      - ./licenses/:/licenses/
      - ./dashboard/:/configuration/
      - ./logs/:/var/log/
    depends_on:
      - dashboard-backend
    links:
      - dashboard-backend:dashboard-backend
    command: dashboard-frontend /configuration/dashboard.yml
