version: '3'

services:
  proxy:
    container_name: proxy
    image: nginx:1.19
    restart: always
    ports:
      - "80:80"
      # - "443:443"  # if TLS is enabled
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # if TLS is disabled
      # - ./nginx/certificate.crt:/etc/nginx/certificates/certificate.crt  # if TLS is enabled
      # - ./nginx/certificate.key:/etc/nginx/certificates/certificate.key  # if TLS is enabled
      # - ./nginx/default_tls.conf:/etc/nginx/conf.d/default.conf  # if TLS is enabled
    depends_on:
      - mongodb
      - dashboard
    links:
      - mongodb:mongodb
      - dashboard:dashboard

  mongodb:
    image: mongo:5
    restart: always
    volumes:
      - ./data/db/:/data/db/
      - ./data/dump/:/dump/

  dashboard:
    image: hilster/dashboard:latest
    restart: always
    environment:
      - ACTIVATION_KEY=OOKF-ZPNF-DPDB-NWJZ  # change me to use a commercial license!
      - DASHBOARD_SERVER=http://proxy:80
      - DASHBOARD_USERNAME=root
      - DASHBOARD_PASSWORD=root  # think before changing the password!
      # - https_proxy=http://username:password@proxy.server:port  # use this for your proxy server
      # - HLM_INSECURE=1  # use this if you are behind a TLS interception proxy to let hlm not verify certificates
    volumes:
      - ./licenses/:/licenses/
      - ./dashboard/:/configuration/
      - ./logs/:/var/log/
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    command: dashboard-server /configuration/dashboard.yml
