version: '3'

services:
  proxy:
    container_name: proxy
    image: nginx:1.19
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mongodb
      - dashboard
    links:
      - mongodb:mongodb
      - dashboard:dashboard

  mongodb:
    image: mongo:4
    restart: always
    volumes:
      - ./data/db/:/data/db/
      - ./data/dump/:/dump/

  dashboard:
    image: hilster/dashboard:latest
    restart: always
    environment:
      - ACTIVATION_KEY=OOKF-ZPNF-DPDB-NWJZ  # change me to use a commercial license!
      - DASHBOARD_SERVER=http://proxy:80
    volumes:
      - ./licenses/:/licenses/
      - ./dashboard/:/configuration/
      - ./logs/:/var/log/
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    command: dashboard-server /configuration/dashboard.yml
